export const Introduction = `
Have you ever stopped in the middle of a busy public location – like school, the airport, or the grocery store - and wondered about the complexities of people’s lives around you? Each and every person has their own unique stories with unique experiences and emotions, and yet, our only understanding of it is that it merely exists. The term for this is *sonder* - coined by John Koenig in *The Dictionary of Obscure Sorrows*. It’s a unique feeling that reminds us of the scale of our own existence in comparison to other people’s lives and the world – it’s an isolating yet connecting moment.
Interestingly, the opposite feeling also exists; the moments when events seem larger than anything else to us. Sometimes, these events stick with us and burden our thoughts later on, and other times, we dread the possibility of such events happening. At the end of the day, these things are out of control – for better or for worse.
Acknowledging that things are beyond our control and realizing that the most important thing is our reaction to them is the most important idea that led me to choosing the theme for this exhibit and curating each art piece. The world will continue to move on despite how big such events may seem to us; it’s all a matter of perspective, and limiting ourselves to a narrow perspective rarely benefits us.
It’s my belief that considering the perspective of others - and to a degree the rest of the universe - can help us move past hiccups of varying sizes that happen in the present. Additionally, there’s no point in dwelling on the past beyond learning from our mistakes. I’m sure many of us can relate to the feeling of stressing over what appears to be the biggest deal in our lives thus far, only for us to move through the moment just fine and realize its minutiae in hindsight. Similarly, a small event (relative to others) may stick with us for a long time afterwards – like an embarrassing moment during a middle school presentation.
The first piece I chose was *Emperor Riding to Heaven on a Dragon* from the Ackland Museum collection. Here, Emperor Huangdi is seen flying to heaven on a dragon. What sticks out to me are the serene landscape and Huangdi’s composure during his ascension. As he sits in a sage pose, he accepts his role moving from the world of living up to the clouds of heaven. Part of me feels a sense of respect and awe while another part of me feels inspired to live my life with as much composure as Huangdi.
The next piece I chose was *Sleep of Reason* by Paul Romano from his personal website. Reminiscent of Huangdi’s facial expression and being watched by several court officials, here, a man sleeps peacefully while the heads belonging to five supernatural beings from Japanese folklore watch over him. There seems to be an untold story within the drawing with open interpretations to the symbolism of its different parts, which is what drew me into paying closer attention. Part of me also relates to the man in the drawing because there have been some nights when I’ve dreamt of something intimidating or frightening and yet continued to sleep peacefully until the morning.
The third piece I chose was *Untitled artwork from the budget Design Store* by Mark Cooper from his personal website. The piece strangely provides a sense of peace despite the intimidating color palette of everything but the face in the clouds. The symbolism and greater meaning of the person sitting on the shoreline and the face in the clouds was something that I wanted to further explore. Unlike the man in *Sleep of Reason*, the man here is awake and appears to be more conscious with his introspection.
The last piece I chose was *You Are Standings in an Open Field (Mount Adams, Washington)* by Jon Rafman from New Art Editions. Unlike the rest of the pieces in the exhibit, this piece provides a first-person perspective and more visible comparison in its sense of scale. The cluttered junk on the table invites gazing eyes to find a pattern, purpose, or hidden meaning behind it all. The painting behind the desk is breathtaking and feels like a modern interpretation of the serene landscape emphasized in *Emperor Riding to Heaven on a Dragon*.
I invite the viewer to discover their own story and to cognize their own thoughts and emotions as they explore each of these pieces. I also hope the viewer can reflect on the message they uncover as they learn more about each piece. And lastly, if there’s anything to take away from this exhibit, it’s the notion that “There are things in this world beyond our control, and that’s okay”.
`;

export const bibliography = `admin. “Jon Rafman - You Are Standing in an Open Field.” New Art Editions, 17 Dec. 2019, https://www.newarteditions.com/jon-rafman-you-are-standing-in-an-open-field/.
Britannica Editors. “Huangdi.” Encyclopedia Britannica, 13 May 2025, https://www.britannica.com/topic/Huangdi.
“Chinese Mythology 101: Four Symbols.” Localiiz, https://www.localiiz.com/post/culture-local-stories-chinese-mythology-101-four-symbols. Accessed 24 Nov. 2025.
“Chinese Xian History, Beliefs & Significance.” Study.Com, https://study.com/academy/lesson/chinese-xian-history-beliefs-culture.html. Accessed 24 Nov. 2025.
Cooksey, Celia. “Melancholy in the Art of Introspection.” ELYSIAN Magazine, 18 Aug. 2023, https://readelysian.com/melancholy-in-art-of-introspection/.
deheunit17. “Perspective in Chinese Painting | Research against Western Styles.” UNIT 17_DE HE, 25 Oct. 2016, https://deheunit17.wordpress.com/2016/10/25/perspective-in-chinese-painting-research-against-western-styles/.
Fact. “Fact Focus: Jon Rafman.” Fact Magazine, 2 Feb. 2023, https://www.factmag.com/2023/02/02/jon-rafman-fact-focus/.
“Learn More about China’s Mythical 3 Sovereigns and 5 Emperors.” ThoughtCo, https://www.thoughtco.com/chinas-three-sovereigns-and-five-emperors-195258. Accessed 24 Nov. 2025.
Masks. https://noh.stanford.edu/staging/masks/#:~:text=Ai%2Dky%C5%8Dgen%20Mask:%20’Noborihige’%20Ky%C5%8Dgen%20masks%20tend%20to,’raising%20beard’%2C%20referring%20to%20its%20bristling%2Dup%20sideburns. Accessed 24 Nov. 2025.
“Paul Romano.” PAUL ROMANO, https://www.workhardened.com. Accessed 24 Nov. 2025.
“Published Work.” Mark-Cooper-Art, https://www.markcooperart.com/published. Accessed 24 Nov. 2025.
Recinos, Alec. “Towards a Postinternet Sublime.” Rhizome, 4 Jan. 2018, p. 1, https://rhizome.org/editorial/2018/jan/04/towards-a-post-internet-sublime/.
Tal, Guy. “The Gestural Language in Francisco Goya’s Sleep of Reason Produces Monsters.” Word & Image, vol. 26, no. 2, Mar. 2010, pp. 115–27. DOI.org (Crossref), https://doi.org/10.1080/02666280902843647.
Theobald, Ulrich. Tian 天, Heaven(Www. Chinaknowledge. De). http://www.chinaknowledge.de/History/Myth/personsheaven.html#:~:text=%22Heaven%22%20(tian%20%E5%A4%A9),the%20necessary%20feeling%20of%20responsibility. Accessed 24 Nov. 2025.
Watson, Stephen. “Balenciaga Taps Artist Jon Rafman to Reimagine Paris Fashion Show.” SURFACE, 9 Oct. 2018, https://www.surfacemag.com/articles/balenciaga-paris-fashion-show-demna-gvasalia-and-artist-jon-rafman/.
Wuxing (Wu-Hsing) | Internet Encyclopedia of Philosophy. https://iep.utm.edu/wuxing/. Accessed 24 Nov. 2025.
Xi’an Huangdi Mausoleum, the Mausoleum for the First Chinese Progenitor. https://www.chinahighlights.com/xian/attraction/huangdi-mausoleum.htm. Accessed 24 Nov. 2025.
https://ackland.emuseum.com/objects/19271/emperor-riding-to-heaven-on-a-dragon?ctx=1bc3170af738fd2c2a52bc9ed85c087e94ac1ed7&idx=10. Accessed 24 Nov. 2025.`;



export const citations = ``

export const cooperLabel = `Mark Cooper is known for his work creating metal band logos and album covers for bands like Berried Alive, Rings of Saturn, and Brand of Sacrifice. He has been making digital paintings since 2008 (Cooper). While Cooper’s style typically takes a lot of inspiration from cosmic horror and H.P. Lovecraft, this piece is more serene and reflective.

The piece depicts a disheveled man sitting in the grass along a coastline while looking above at a large and ethereal face in the clouds above. Some of Cooper’s cosmic horror style can be seen if you pay close attention to the left side of the clouds, specifically the creatures, planets, and the skull-shaped cloud.

The perspective of the piece juxtaposes the small and seemingly insignificant nature of the man in comparison to the overwhelming cosmic presence of the face in the clouds. The immense size of the face in the clouds initially seems intimidating but could ultimately be interpreted as a serene and contemplative presence, especially when contrasted with the cosmic horror behind it. The man sits on the ground in a position that suggests contemplation and introspection. One interpretation of the cloud-face is that it belongs to the man: a manifestation of his inner thoughts, and a reminder that our thoughts can feel bigger to us internally. Likewise, the man gazing at the cloud-face in such a calm manner suggests that we can still find peace with our lives despite acknowledging the presence of forces beyond our control.
`

export const romanoLabel = `Paul Romano is known for his work with the Atlanta heavy metal band *Mastodon*, painting five out of their eight studio album art covers. While Romano often paints, he still switches between a variety of different mediums in his works; it is likely Romano decided to use charcoal in this piece due to its range of light and dark values and the grayscale color palette to create as much contrast and emphasis between the different of the drawing. The piece is likely inspired by the famous etching *The Sleep of Reason Produces Monsters* by Spanish artist Francisco Goya, where a man sleeps on his hand in the melancholy pose as he dreams of different animals (Tal, 1).

The drawing depicts a man sleeping peacefully in a dark room while the heads of 5 different demons peer from behind a curtain above the man. The lack of light emanating from these demons implies that the man is only dreaming them. The demon heads are likely inspired by traditional Japanese masks.
The top right demon looks like Ko-omote Noh mask – a depiction of classic Heian era aristocratic style and innocent beauty often used in performances to depict a young girl or supernatural entity.
The demon down and to the left is likely meant to be an Oni mask – also used in performances, it wards off evil spirits and represents a duality between good and evil or light and dark.
The demon to the right is likely a Karasu Tengu (supernatural bird-like beings) mask. Its significance is very similar to the Oni mask.
The last two masks are likely Kyōgen masks – exaggerated faces used in performances to portray supernatural characters.  (Pellecchia)

The demons could be seen as distorted representations of the man’s problems or stressors – a potential interpretation to the Renaissance idea of melancholy, where heavy emotions can impact intellectual and creative thought. Notably, the demon heads reference masks from traditional Japanese performance, suggesting a connection between creativity, expression, and the man’s inner experience. While the demons appear large, their power is ultimately confined to the man’s dream, reminding us that the perceived scale of our worries is limited by perspective – a reflection of how events that seem overwhelming in the moment are often smaller in the grander scheme of life.
`

export const emperorLabel = `The text in the painting can be translated as “Return to Heaven Huangdi” or “Back to Heaven Huangdi”, where the character for “Huangdi” also means “Yellow Emperor”, and the character for “Heaven” says “Tian” which refers to the Chinese concept of supreme divine force and will. The painting depicts the Yellow Emperor ascending to heaven on a dragon, in reference to the famous legend in Chinese culture.\n
In Chinese culture, Emperor Huangdi is said to be a legendary sovereign from pre-dynasty China and has played an important role in much of Chinese history and culture - most notably being one of the first emperors of China and being one of the Three Sovereigns and Five Emperors. 
In the legend, it is said that as Huangdi died after living for over one hundred years, leaving only his hat and clothes behind as he ascended to heaven on the Yellow Dragon. The Yellow Dragon is one of the mythical creatures of *Sixiang* - the Four Symbols - and the embodiment of the element Earth in *Wuxing* - the five elements. But most importantly, the Yellow Dragon is stated to be the reincarnation of the Yellow Emperor. Throughout Chinese history, the mausoleum containing the Yellow Emperor's clothes and hat - known as “The First Tomb Under Heaven” - has been highly respected by previous leaders and dynasties.
The painting depicts Huangdi in the sky, in Heaven, on a dragon, with people beneath him looking up. The people below are dressed in robes holding ceremonial fans, likely being court officials. The perspective in the painting is common with many others during the period - the elevation provides visibility to Huangdi in the sky and the officials beneath him. In non-Western art, the use of perspective in this way highlights the author's emotions rather than depict the subject(s) in one-to-one detail. It reminds us that someone painted this piece from their own perspective, emotions, and experiences, rather than attempting to realistically emulate whatever is being painted. Huangdi's posture is one that implies sageness, while his facial expression suggests peace and introspection, and the landscape uses light colors to evoke a feeling of serenity and peace - which makes sense from the perspective of a sage accepting the divine will of Tian. 
At this point, Huangdi would be considered a *xian* - an immortal or mythical being according to Taoist and Chinese folklore. While the artist is not known, it can be assumed that they hold respect for Emperor Huangdi and the legend of his ascension to Heaven based on this depiction and the longstanding tradition to pay respects at his mausoleum. The title implies that Huangdi first came down from heaven before ultimately returning.
Historically, the medium of watercolor on silk is used for making paintings and banners for ancient tombs. It is possible that the artist is paying respect to such culture and history through this medium.
`

export const rafmanLabel = `Jon Rafman is known for his post-Internet art where he uses Google Street View, the videogame Second Life, and other internet-inspired mediums to create art. Some of his notable creations include artwork for Lil Yachty (Let’s Start Here), Kanye West (Vultures), and Travis Scott (Utopia) (FactMag). Some of his works are publicly displayed at the Museum of Modern Art, the Stedeljik Museum, MAXXI, and more. He has also collaborated with luxury fashion brand Balenciaga in producing an LED tunnel for their 2019 spring-summer show (Watson) due to his experience with virtual reality, Google Street View, and more.

This piece is one of many sharing the title of *You Are Standing in an Open Field* – the concept of each entry in the series is that you are looking from the perspective of someone at their workstation while the computer screen is replaced by a natural landscape (Howard). In this instance, the sublime view of Mount Adams, Washington, is displayed while a desk is cluttered with a variety of junk. A keyboard with sticky notes, sci-fi novels, a few Juuls, pens and pencils, a bottle of Ramune soda, jewelry, a gun, an inhaler, and pills are just some of the random items in view. The items on display can be interpreted as a representation of the average consumer’s life – it could be anyone’s desk. While not everyone might enjoy reading books by Phillip K. Dick, Rafman’s suggestion that consumerism has such a commonplace role in our daily lives is still understood.

The messy and chaotic desk juxtaposes the sublime and beautiful view of Mount Adams. The comparison Rafman attempts to make is quite clear: the small stresses of our daily lives seem much bigger when they’re at the foreground of our mind. When taking a step back and comparing this with the rest of the scenery, it’s clear that such an idea is only relative to our own perspective. In a way, here Rafman is asking the question “Why does that matter when You Are Standing in an Open Field?”. With the view of Mount Adams behind a cluttered desk, Rafman reminds us that recognizing the larger scale of existence and acknowledging the things out of our control can help us move through the stresses of the present.
`

export const labels = {cooperLabel: cooperLabel, romanoLabel: romanoLabel, emperorLabel: emperorLabel, rafmanLabel: rafmanLabel}